package utils;
import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.WebDriver;
public class clsConstants {
    public static WebDriver driver = null;
    public static AppiumDriver appdriver = null;
    public static String strDataBegin = "Browser";
    public static int intRowNo;
    public static String strTestStatus;
    public static String strOutput;
    public static String xmlRepository;
    public static String companyName;
    public static String opportunityName;
    protected static String NewcustomerEmail = "vq6p0AutoGenerated@nedbank.com"; //"constantisnull";
    public  static String firstname = null;
    public  static String lastname = null;
    protected static String pitchDeckName = "constantisnull";
}
