@run1
Feature: SimplyBiz Web Registration Feature

  Scenario Outline: Successful Registration on SimplyBiz Web Application New business Owner
    Given User launch SimplyBiz "Register" web application
    And User Selects quest Icon and clicks on Sign up here link
    And User enters "<firstname>", "<Lastname>","<Email>", "<Cellphone>" and "<Password>"
    And User Selects the terms and conditions and clicks on Next button
    And User selects "<Selectwhatdefinesyouthemost>" value and clicks Next button
    And User enters "<companyname>", "<industry>","<telluswhyyouhavejoinedSimplyBiz>", "<tellusmoreaboutyourself>"
    And User clicks Next button
    And  System displays text "You are almost done"
    When User clicks Submit button
    Then page is displayed with "<text1>"
    And User clicks button Continue
  #  Then Congratulations page is displayed
  #  And User is asked to enter code
    And User Closes the Browser
    Examples:
      | firstname | Lastname | Email | Cellphone | Password | Selectwhatdefinesyouthemost | companyname | industry | telluswhyyouhavejoinedSimplyBiz | tellusmoreaboutyourself | text1 |
      | Test     | Testing |AutoGenerated| 0722410251 | TestTesting1@ | New business owner | TestComp | Technology | I am looking for support in growing my small business | Testing | Your registration has been successfully completed |

  Scenario Outline: Verify that email is send to customer after registration
      Given User launch SimplyBiz "Admin" web application
      And User "<role>" enters username "<username>" and password "<password>"
      And User clicks on Log in button
      And User Logged in Successfully
      And Admin User is logged in successfully
      And User navigates to Dashboard and selects System and then message queue
      And User enters to email "<CustEmail>"
      Then Message queue displays the email, timestamp from and to
      And  User Closes the Browser
      Examples:
        | role |username | password|CustEmail|
      |Admin|DefaultAdmin|TestTesting1@|AutoGenerated|


  Scenario Outline: Activate New Customer
   Given User launch SimplyBiz "Admin" web application
   And User "<role>" enters username "<username>" and password "<password>"
   And User clicks on Log in button
   And User Logged in Successfully
   And Admin User is logged in successfully
   And User navigates to Dashboard and selects customers
   And User enters customer "<firstname>" and "<lastname>" that needs to be activated and clicks search button
   And User Selects Customer and clicks edit button
   And User selects active checkbox
   When User clicks save button
   Then The system displays message "<expectedMsg>"
   And User clicks logout
   And Landing page is displayed
   And  User Closes the Browser
 Examples:
   | role |username | password |firstname|lastname| expectedMsg|
   |Admin|DefaultAdmin|TestTesting1@|1z8xTest|Testing|The customer has been updated successfully|

# Scenario Outline: Logout from SimplyBiz
#   Given User is logged in as "<role>"
#   When User clicks logout
#   Then Landing page is displayed
# Examples:
#   |role|
#   |admin|

  Scenario Outline: Login as a New registered company
    Given User launch SimplyBiz "Login" web application
    And User "<role>" enters username "<username>" and password "<password>"
    When User clicks on Log in button
    Then User Logged in Successfully
    And User Closes the Browser
    Examples:
     | role |username | password |
     | Customer|AutoGenerated|TestTesting1@|

  Scenario: Successful Registration on SimplyBiz Web Application Subject matter expert (SME)
  Scenario: Successful Registration on SimplyBiz Web Application Looking to grow
  Scenario: Successful Registration on SimplyBiz Web Application Established business
