@run2
Feature:  Login SimplyBiz

  Scenario Outline: Successful Login to Simplybiz Web Application
    Given User launch SimplyBiz "Login" web application
    And User "<role>" enters username "<username>" and password "<password>"
    When User clicks on Log in button
    Then User Logged in Successfully
    And User Closes the Browser

    Examples:
      | role |username | password |
      | Customer | AutoGenerated | TestTesting1@|

